#ifndef APCAM_TARGET_IDS_H
#define APCAM_TARGET_IDS_H
#define APCAM_TARGET_MT11 1
#define APCAM_TARGET_A8 2
#define APCAM_TARGET_ZR10 3
#define APCAM_TARGET_Z1_MINI 4
#define APCAM_LENS_TYPE_RGB 1
#define APCAM_LENS_TYPE_THERMAL 2
#define APCAM_PROTOCOL_SIYI 1
#define APCAM_PROTOCOL_XFROBOT 2
/* Stable resolution IDs match the persisted/MAVLink resolution parameters. */
#define APCAM_RES_720P 0
#define APCAM_RES_1080P 1
#define APCAM_RES_2160P 2
#define APCAM_RES_1440P 3
#define APCAM_RES_MASK_720P (1U << APCAM_RES_720P)
#define APCAM_RES_MASK_1080P (1U << APCAM_RES_1080P)
#define APCAM_RES_MASK_2160P (1U << APCAM_RES_2160P)
#define APCAM_RES_MASK_1440P (1U << APCAM_RES_1440P)
#define APCAM_FOV_FOCAL_LENGTH 1
#define APCAM_FOV_ENDPOINTS 2
#endif
