#!/usr/bin/env python3
"""Plane AUTO mission survey through AP_Camera and the gimbal manager lease."""
import argparse
import json
import os
from pathlib import Path
import subprocess
import sys
import time

os.environ.setdefault('MAVLINK20', '1')
from pymavlink import mavutil
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'sitl'))
from test_mavlink_parameters import port, stop, wait_ready

ROOT = Path(__file__).resolve().parents[1]
M = mavutil.mavlink


def run(args):
    out = args.output.resolve()
    out.mkdir(parents=True, exist_ok=True)
    cp, gp, ap = port(), port(), port()
    cfg = out/'camera.ini'
    cfg.write_text('[survey]\nburst=2\ndwell_ms=800\n')
    params = out/'plane.parm'
    params.write_text('MNT1_TYPE 6\nCAM1_TYPE 6\nNET_ENABLE 1\nNET_P1_TYPE 3\nNET_P1_PROTOCOL 2\n'
                      f'NET_P1_IP0 127\nNET_P1_IP1 0\nNET_P1_IP2 0\nNET_P1_IP3 1\nNET_P1_PORT {cp}\n'
                      'ARMING_CHECK 0\nTERRAIN_ENABLE 1\nLOG_DISARMED 1\nAIRSPEED_CRUISE 25\n'
                      'RTL_AUTOLAND 0\n')
    env = dict(os.environ, CAMERA_APP_CONFIG=str(cfg), CAMERA_APP_BACKEND='mt11',
               CAMERA_APP_UART=f'udp://127.0.0.1:{gp}', CAMERA_APP_PORT=str(port()),
               CAMERA_APP_MAVLINK_TCP_PORT=str(cp), CAMERA_APP_MAVLINK_UDP_PORT='0',
               CAMERA_APP_RTSP_PORT=str(port()), CAMERA_APP_RAW_THERMAL_PORT=str(port()),
               CAMERA_APP_CAPTURE_ROOT=str(out/'capture'), CAMERA_APP_RECORD_ROOT=str(out/'record'),
               CAMERA_APP_READY_PATH=str(out/'camera.ready'))
    for key in ('CAMERA_APP_SITL_TERRAIN', 'CAMERA_APP_SITL_VIDEO1', 'CAMERA_APP_SITL_VIDEO2'):
        env.pop(key, None)
    for p in out.glob('*.ready'):
        p.unlink()
    processes, logs, messages = [], [], []
    link = None

    def launch(name, command, **kwargs):
        log = (out/(name+'.log')).open('w')
        logs.append(log)
        proc = subprocess.Popen(command, stdout=log, stderr=subprocess.STDOUT, **kwargs)
        processes.append(proc)
        return proc

    def receive(timeout=.2):
        message = link.recv_match(blocking=True, timeout=timeout)
        if message is not None:
            kind = message.get_type()
            if kind == 'TERRAIN_REQUEST':
                # Supply a flat test terrain database. TERRAIN_REPORT itself
                # is generated by the real flight controller on request.
                for bit in range(56):
                    if message.mask & (1 << bit):
                        link.mav.terrain_data_send(message.lat, message.lon, message.grid_spacing, bit, [584]*16)
            if kind in ('CAMERA_IMAGE_CAPTURED', 'GIMBAL_MANAGER_STATUS', 'STATUSTEXT', 'COMMAND_ACK', 'MISSION_CURRENT'):
                messages.append(message.to_dict())
            return message
        return None

    def wait(predicate, timeout=20):
        deadline = time.monotonic()+timeout
        while time.monotonic() < deadline:
            message = receive()
            if message is not None and predicate(message):
                return message
        raise TimeoutError('expected MAVLink event')

    def command(cmd, params, component=1):
        deadline = time.monotonic()+20
        next_send = 0
        while time.monotonic() < deadline:
            if time.monotonic() >= next_send:
                link.mav.command_long_send(1, component, cmd, 0, *(params+[0]*(7-len(params))))
                next_send = time.monotonic()+2
            m = receive()
            if m is not None and m.get_type() == 'COMMAND_ACK' and m.command == cmd and m.get_srcComponent() == component:
                return m
        raise TimeoutError(f'command {cmd} to component {component}')

    try:
        gimbal = launch('gimbal', [sys.executable, str(ROOT/'sitl/gimbal_sim.py'), '--port', str(gp),
                                  '--ready-file', str(out/'gimbal.ready')])
        wait_ready(out/'gimbal.ready', gimbal)
        camera = launch('camera', [str(ROOT/'build/sitl/camera-app')], env=env)
        wait_ready(out/'camera.ready', camera)
        plane = launch('plane', [str(args.arduplane.resolve()), '--wipe', '-I', str(100+ap%1000), '--serial1', 'none', '--serial2', 'none', '--model', 'plane', '--speedup', '1',
                                '--home=-35.362938,149.165085,584,0', '--serial0', f'tcp:{ap}',
                                '--defaults', str(params)], cwd=out)
        deadline = time.monotonic()+30
        while link is None and time.monotonic() < deadline:
            try:
                link = mavutil.mavlink_connection(f'tcp:127.0.0.1:{ap}', source_system=255, source_component=190)
            except OSError:
                time.sleep(.2)
        assert link is not None and plane.poll() is None
        wait(lambda m: m.get_type() == 'HEARTBEAT')
        for msgid, interval in ((M.MAVLINK_MSG_ID_GLOBAL_POSITION_INT, 100000),
                                (M.MAVLINK_MSG_ID_GIMBAL_MANAGER_STATUS, 500000)):
            command(M.MAV_CMD_SET_MESSAGE_INTERVAL, [msgid, interval])
        command(M.MAV_CMD_REQUEST_MESSAGE, [M.MAVLINK_MSG_ID_CAMERA_INFORMATION], 100)
        # Mission mode has a selected camera ID, survives import/storage/export,
        # and is executed through AP_Camera when AUTO reaches this segment.
        home_lat, home_lon = -35.362938, 149.165085
        items = [
            (M.MAV_CMD_NAV_WAYPOINT, 0, 0, home_lat, home_lon, 584),
            (M.MAV_CMD_NAV_TAKEOFF, 12, 0, home_lat+.001, home_lon, 400),
            (M.MAV_CMD_NAV_WAYPOINT, 0, 0, home_lat+.015, home_lon, 400),
            (M.MAV_CMD_SET_CAMERA_MODE, 100, 2, 0, 0, 0),
            (M.MAV_CMD_NAV_WAYPOINT, 0, 0, home_lat+.08, home_lon, 400),
            (M.MAV_CMD_SET_CAMERA_MODE, 100, 0, 0, 0, 0),
            (M.MAV_CMD_NAV_LOITER_UNLIM, 0, 0, home_lat+.09, home_lon, 400),
        ]
        link.mav.mission_count_send(1, 1, len(items))
        while True:
            m = wait(lambda m: m.get_type() in ('MISSION_REQUEST_INT', 'MISSION_REQUEST', 'MISSION_ACK'))
            if m.get_type() == 'MISSION_ACK':
                assert m.type == M.MAV_MISSION_ACCEPTED, m
                break
            cmd, p1, p2, lat, lon, alt = items[m.seq]
            frame = M.MAV_FRAME_MISSION if cmd == M.MAV_CMD_SET_CAMERA_MODE else M.MAV_FRAME_GLOBAL_RELATIVE_ALT_INT
            link.mav.mission_item_int_send(1, 1, m.seq, frame, cmd, 0, 1, p1, p2, 0, 0,
                                          round(lat*1e7), round(lon*1e7), alt)
        link.mav.mission_request_int_send(1, 1, 3)
        mode_item = wait(lambda m: m.get_type() == 'MISSION_ITEM_INT' and m.seq == 3)
        assert mode_item.command == M.MAV_CMD_SET_CAMERA_MODE and mode_item.param1 == 100 and mode_item.param2 == 2, mode_item
        # Give EKF/GPS and the mount discovery time to initialise.
        deadline = time.monotonic()+12
        while time.monotonic() < deadline:
            receive()
        command(M.MAV_CMD_COMPONENT_ARM_DISARM, [1, 21196])
        link.mav.set_mode_send(1, M.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED, 10)
        first = wait(lambda m: m.get_type() == 'CAMERA_IMAGE_CAPTURED' and m.capture_result == 1, args.timeout)
        assert first.relative_alt > 300000, first
        deadline = time.monotonic()+70
        navigation_seen = False
        while time.monotonic() < deadline:
            receive()
            status_path = Path(str(cfg)+'.survey.json')
            if status_path.exists():
                navigation_seen |= json.loads(status_path.read_text()).get('path_source') == 'navigation'
        captures = [m for m in messages if m['mavpackettype'] == 'CAMERA_IMAGE_CAPTURED' and m['capture_result'] == 1]
        assert len(captures) >= 9, len(captures)
        assert navigation_seen, 'camera did not reconstruct the AUTO waypoint leg'
        assert any(m.get('primary_control_compid') == 154 for m in messages), 'no device ownership confirmation'
        # Explicit manager pointing must interrupt survey, not fight it.
        command(M.MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW, [-45, 0, 0, 0, 0, 0, 154])
        deadline = time.monotonic()+4
        while time.monotonic() < deadline:
            receive()
        status = json.loads(Path(str(cfg)+'.survey.json').read_text())
        assert 'paused' in status['state'], status
        # Restart by command, then kill the camera and check lease expiry.
        ack = command(M.MAV_CMD_SET_CAMERA_MODE, [100, 2])
        assert ack.result == M.MAV_RESULT_ACCEPTED, ack
        wait(lambda m: m.get_type() == 'GIMBAL_MANAGER_STATUS' and m.primary_control_compid == 154)
        stop(camera)
        wait(lambda m: m.get_type() == 'GIMBAL_MANAGER_STATUS' and m.primary_control_compid == 0, 8)
        print(f'PASS Plane AUTO: mission mode roundtrip, {len(captures)} captures at ~400m AGL, takeover and crash lease expiry')
    finally:
        (out/'events.json').write_text(json.dumps(messages, indent=2))
        if link:
            link.close()
        for proc in reversed(processes):
            stop(proc)
        for log in logs:
            log.close()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--arduplane', type=Path, default=Path('/data/APM.mavlink_camera/build/sitl/bin/arduplane'))
    parser.add_argument('--output', type=Path, default=ROOT/'build/survey-plane')
    parser.add_argument('--timeout', type=float, default=240)
    run(parser.parse_args())
