#include "camera_app/mavlink.h"

#include "checksum.h"

#include <assert.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static int hex_value(char value)
{
    if (value >= '0' && value <= '9') return value - '0';
    if (value >= 'a' && value <= 'f') return value - 'a' + 10;
    assert(0 && "invalid test vector");
    return 0;
}

static size_t decode_hex(const char *text, uint8_t *data, size_t capacity)
{
    size_t text_length = strlen(text);
    assert((text_length & 1U) == 0U);
    assert(text_length / 2U <= capacity);
    for (size_t i = 0; i < text_length / 2U; i++) {
        data[i] = (uint8_t)((hex_value(text[i * 2U]) << 4U) |
                            hex_value(text[i * 2U + 1U]));
    }
    return text_length / 2U;
}

/* Feed a whole frame through a fresh parser; only the last byte may
 * complete or reject it. */
static int parse_packet(const uint8_t *packet, size_t length,
                        mavlink_message_t *message)
{
    struct ca_mavlink_parser parser;
    int result = 0;
    ca_mavlink_parser_init(&parser);
    for (size_t i = 0; i < length; i++) {
        result = ca_mavlink_parse_byte(&parser, packet[i], message);
        if (i + 1U != length) assert(result == 0);
    }
    return result;
}

static void test_generated_vectors(void)
{
    /* Frames generated by pymavlink common.xml, independently checking both
     * wire versions, field ordering, CRC extras and MAVLink 2 zero trimming. */
    static const char command_long_hex[] =
        "fd200000002abe4c00000000004000004842000000000000000000000000000000"
        "000000000013020164b1fb";
    static const char heartbeat_v1_hex[] =
        "fe09072abe00000000000608000403f4bd";
    static const char global_position_hex[] =
        "fd1200000001012100007b00000094feebea12cfe858c0270900803e071e";
    uint8_t packet[MAVLINK_MAX_PACKET_LEN];
    mavlink_message_t message;
    mavlink_command_long_t command;
    mavlink_heartbeat_t heartbeat;
    mavlink_global_position_int_t position;
    size_t length = decode_hex(command_long_hex, packet, sizeof(packet));

    assert(parse_packet(packet, length, &message) == 1);
    assert(message.msgid == MAVLINK_MSG_ID_COMMAND_LONG);
    assert(message.sysid == 42U);
    assert(message.compid == 190U);
    assert(message.len == 32U);
    mavlink_msg_command_long_decode(&message, &command);
    assert(command.command == MAV_CMD_SET_CAMERA_ZOOM);
    assert(command.target_system == 1U && command.target_component == 100U);
    assert(command.param1 == 2.0f && command.param2 == 50.0f);
    assert(command.param3 == 0.0f && command.param7 == 0.0f);
    assert(command.confirmation == 0U); /* trimmed, zero-filled */

    packet[length - 1U] ^= 1U;
    assert(parse_packet(packet, length, &message) == -1);

    length = decode_hex(heartbeat_v1_hex, packet, sizeof(packet));
    assert(parse_packet(packet, length, &message) == 1);
    assert(message.msgid == MAVLINK_MSG_ID_HEARTBEAT);
    assert(message.magic == MAVLINK_STX_MAVLINK1);
    assert(message.sysid == 42U);
    assert(message.compid == 190U);
    assert(message.len == 9U);
    mavlink_msg_heartbeat_decode(&message, &heartbeat);
    assert(heartbeat.type == MAV_TYPE_GCS);
    assert(heartbeat.autopilot == MAV_AUTOPILOT_INVALID);
    assert(heartbeat.system_status == MAV_STATE_ACTIVE);
    assert(heartbeat.mavlink_version == 3U);

    packet[length - 2U] ^= 0x80U;
    assert(parse_packet(packet, length, &message) == -1);

    length = decode_hex(global_position_hex, packet, sizeof(packet));
    assert(parse_packet(packet, length, &message) == 1);
    assert(message.msgid == MAVLINK_MSG_ID_GLOBAL_POSITION_INT);
    assert(message.sysid == 1U);
    assert(message.compid == 1U);
    assert(message.len == 18U);
    mavlink_msg_global_position_int_decode(&message, &position);
    assert(position.time_boot_ms == 123U);
    assert(position.lat == -353632620);
    assert(position.lon == 1491652370);
    assert(position.alt == 600000);
    assert(position.relative_alt == 16000);
    assert(position.vx == 0 && position.vy == 0 && position.vz == 0);
    assert(position.hdg == 0U); /* trimmed, zero-filled */
}

static void test_round_trip(void)
{
    uint8_t packet[MAVLINK_MAX_PACKET_LEN];
    mavlink_status_t tx = {0};
    mavlink_message_t message;
    mavlink_message_t received;
    mavlink_heartbeat_t heartbeat = {
        .type = MAV_TYPE_CAMERA,
        .autopilot = MAV_AUTOPILOT_INVALID,
        .system_status = MAV_STATE_ACTIVE,
    };
    mavlink_heartbeat_t decoded;
    mavlink_camera_settings_t settings = {.time_boot_ms = 0x01020304U};
    mavlink_camera_settings_t decoded_settings;
    size_t length;

    (void)mavlink_msg_heartbeat_encode_status(42U, 190U, &tx, &message,
                                              &heartbeat);
    length = ca_mavlink_to_wire(packet, sizeof(packet), &message);
    assert(length == 21U);
    assert(packet[0] == MAVLINK_STX && packet[1] == 9U);
    assert(packet[2] == 0U && packet[3] == 0U); /* unsigned, no flags */
    assert(packet[4] == 0U);                    /* first sequence number */
    assert(packet[5] == 42U && packet[6] == 190U);
    assert(parse_packet(packet, length, &received) == 1);
    assert(received.msgid == MAVLINK_MSG_ID_HEARTBEAT);
    mavlink_msg_heartbeat_decode(&received, &decoded);
    assert(decoded.type == MAV_TYPE_CAMERA);
    assert(decoded.autopilot == MAV_AUTOPILOT_INVALID);
    assert(decoded.system_status == MAV_STATE_ACTIVE);
    assert(decoded.mavlink_version == 3U);

    /* The component status carries the sequence number. */
    (void)mavlink_msg_heartbeat_encode_status(42U, 190U, &tx, &message,
                                              &heartbeat);
    assert(message.seq == 1U);
    ca_mavlink_restamp(&message, &tx);
    assert(message.seq == 2U);
    length = ca_mavlink_to_wire(packet, sizeof(packet), &message);
    assert(length == 21U && packet[4] == 2U);
    assert(parse_packet(packet, length, &received) == 1);
    assert(received.seq == 2U);

    /* MAVLink 2 output trims trailing zero bytes; decode restores them. */
    (void)mavlink_msg_camera_settings_encode_status(1U, 100U, &tx, &message,
                                                    &settings);
    assert(message.len == 4U);
    length = ca_mavlink_to_wire(packet, sizeof(packet), &message);
    assert(length == MAVLINK_NUM_NON_PAYLOAD_BYTES + 4U);
    assert(parse_packet(packet, length, &received) == 1);
    assert(received.len == 4U);
    mavlink_msg_camera_settings_decode(&received, &decoded_settings);
    assert(decoded_settings.time_boot_ms == 0x01020304U);
    assert(decoded_settings.mode_id == 0U);
    assert(decoded_settings.zoomLevel == 0.0f);
    assert(decoded_settings.focusLevel == 0.0f);

    assert(ca_mavlink_to_wire(packet, 2U, &message) == 0U);
    assert(ca_mavlink_to_wire(packet, length - 1U, &message) == 0U);
    assert(ca_mavlink_to_wire(packet, length, &message) == length);
}

static void test_unknown_and_resync(void)
{
    struct ca_mavlink_parser parser;
    uint8_t packet[MAVLINK_MAX_PACKET_LEN];
    uint8_t unknown[MAVLINK_MAX_PACKET_LEN];
    mavlink_status_t tx = {0};
    mavlink_message_t message;
    mavlink_message_t received;
    mavlink_heartbeat_t heartbeat = {.type = MAV_TYPE_GIMBAL};
    size_t length;
    int result = 0;

    (void)mavlink_msg_heartbeat_encode_status(1U, 154U, &tx, &message,
                                              &heartbeat);
    length = ca_mavlink_to_wire(packet, sizeof(packet), &message);

    /* A well formed frame with an id outside the dialect is dropped, and
     * the following frame still parses on the same link. */
    memcpy(unknown, packet, length);
    unknown[7] = 0xffU;
    unknown[8] = 0xffU;
    unknown[9] = 0xfeU;
    ca_mavlink_parser_init(&parser);
    for (size_t i = 0; i < length; i++) {
        result = ca_mavlink_parse_byte(&parser, unknown[i], &received);
        if (i + 1U != length) assert(result == 0);
    }
    assert(result == -1);
    for (size_t i = 0; i < length; i++) {
        result = ca_mavlink_parse_byte(&parser, packet[i], &received);
    }
    assert(result == 1 && received.msgid == MAVLINK_MSG_ID_HEARTBEAT);

    /* Noise between frames is skipped. */
    assert(ca_mavlink_parse_byte(&parser, 0x00U, &received) == 0);
    assert(ca_mavlink_parse_byte(&parser, 0x42U, &received) == 0);
    for (size_t i = 0; i < length; i++) {
        result = ca_mavlink_parse_byte(&parser, packet[i], &received);
    }
    assert(result == 1 && received.compid == 154U);

    /* A signed frame is accepted on its CRC; signing is not configured. */
    packet[2] = MAVLINK_IFLAG_SIGNED;
    {
        uint16_t crc = crc_calculate(packet + 1U, 9U + packet[1]);
        crc_accumulate(mavlink_get_msg_entry(message.msgid)->crc_extra, &crc);
        packet[10U + packet[1]] = (uint8_t)crc;
        packet[11U + packet[1]] = (uint8_t)(crc >> 8U);
    }
    memset(packet + length, 0, MAVLINK_SIGNATURE_BLOCK_LEN);
    assert(parse_packet(packet, length + MAVLINK_SIGNATURE_BLOCK_LEN,
                        &received) == 1);
    assert(received.msgid == MAVLINK_MSG_ID_HEARTBEAT);

    /* A signed frame with a bad CRC is dropped together with its signature
     * block, even when the signature looks like a frame start, and the next
     * unsigned frame parses. */
    packet[length - 1U] ^= 0x10U;
    packet[length] = MAVLINK_STX;
    packet[length + 1U] = 0xffU;
    ca_mavlink_parser_init(&parser);
    for (size_t i = 0; i < length + MAVLINK_SIGNATURE_BLOCK_LEN; i++) {
        assert(ca_mavlink_parse_byte(&parser, packet[i], &received) != 1);
    }
    for (size_t i = 0; i < length; i++) {
        result = ca_mavlink_parse_byte(&parser, unknown[i], &received);
        assert(result != 1);
    }
    (void)mavlink_msg_heartbeat_encode_status(1U, 154U, &tx, &message,
                                              &heartbeat);
    length = ca_mavlink_to_wire(packet, sizeof(packet), &message);
    for (size_t i = 0; i < length; i++) {
        result = ca_mavlink_parse_byte(&parser, packet[i], &received);
        if (i + 1U != length) assert(result == 0);
    }
    assert(result == 1 && received.msgid == MAVLINK_MSG_ID_HEARTBEAT);

    /* Nor is a signature ending in a frame-start byte reused as one. */
    memcpy(unknown, packet, length);
    unknown[2] = MAVLINK_IFLAG_SIGNED;
    memset(unknown + length, 0, MAVLINK_SIGNATURE_BLOCK_LEN);
    unknown[length + MAVLINK_SIGNATURE_BLOCK_LEN - 1U] = MAVLINK_STX;
    ca_mavlink_parser_init(&parser);
    for (size_t i = 0; i < length + MAVLINK_SIGNATURE_BLOCK_LEN; i++) {
        assert(ca_mavlink_parse_byte(&parser, unknown[i], &received) != 1);
    }
    for (size_t i = 0; i < length; i++) {
        result = ca_mavlink_parse_byte(&parser, packet[i], &received);
        if (i + 1U != length) assert(result == 0);
    }
    assert(result == 1 && received.msgid == MAVLINK_MSG_ID_HEARTBEAT);
}

int main(void)
{
    test_generated_vectors();
    test_round_trip();
    test_unknown_and_resync();
    puts("mavlink protocol tests passed");
    return 0;
}
