#!/usr/bin/env python3
"""Embed committed web icons; optionally regenerate ICOs from the source SVG."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets'


def render():
    # Only asset regeneration needs these libraries. Firmware/CI builds use
    # the committed ICOs and require only Python's standard library.
    import io
    import gi
    gi.require_version('Rsvg', '2.0')
    from gi.repository import Rsvg
    import cairo
    from PIL import Image
    source = Rsvg.Handle.new_from_file(str(ASSETS / 'camera-gimbal.svg'))
    sizes = (16, 24, 32, 48, 64, 128, 256)
    images = {}
    for size in sizes:
        surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, size, size)
        viewport = Rsvg.Rectangle()
        viewport.x = viewport.y = 0
        viewport.width = viewport.height = size
        source.render_document(cairo.Context(surface), viewport)
        buffer = io.BytesIO()
        surface.write_to_png(buffer)
        buffer.seek(0)
        images[size] = Image.open(buffer).convert('RGBA')
    for name, selected in [('camera-gimbal.ico', sizes), ('favicon.ico', (16, 32, 48))]:
        images[max(selected)].save(ASSETS / name, format='ICO',
            sizes=[(s, s) for s in selected], append_images=[images[s] for s in selected])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--render', action='store_true', help='regenerate ICOs using librsvg, Cairo and Pillow')
    parser.add_argument('--output', type=Path, default=ROOT / 'web/build/icons.h')
    args = parser.parse_args()
    if args.render:
        render()
    output = ['/* Generated by tools/build_icons.py; do not edit. */\n']
    for symbol, filename in [('favicon_svg', 'camera-gimbal.svg'), ('favicon_ico', 'favicon.ico')]:
        data = (ASSETS / filename).read_bytes()
        output.append('static const unsigned char %s[] = {\n' % symbol)
        for start in range(0, len(data), 16):
            output.append('    ' + ','.join('0x%02x' % b for b in data[start:start + 16]) + ',\n')
        output.append('};\n')
    contents = ''.join(output)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text() != contents:
        args.output.write_text(contents)


if __name__ == '__main__':
    main()
