#!/usr/bin/env python3
"""Regenerate the portable IANA name/rule table from a pinned tzdata release.

Normal builds use the checked-in header and need neither zic nor network access.
The selected zones use recurring POSIX rules on every supported camera libc.
Reject source changes that introduce exceptions not representable by those rules.
"""
import argparse
from datetime import datetime, timezone
import hashlib
from pathlib import Path
import struct
import subprocess
import tarfile
import tempfile
import time
import os
import re
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parents[1]
VERSION = '2026d'
SHA256 = '0cb2aa8e333c3dc049badc42a0c61f21987b8cd44e107fa900bad764aacc7767'
SOURCES = 'africa antarctica asia australasia europe northamerica southamerica etcetera backward'.split()


def transitions(data):
    def counts(pos):
        return struct.unpack_from('>6I', data, pos + 20)
    gmt, std, leap, n, types, chars = counts(0)
    pos = 44 + n * 5 + types * 6 + chars + leap * 8 + std + gmt
    _, _, _, n, _, _ = counts(pos)
    return struct.unpack_from(f'>{n}q', data, pos + 44)


def generate(archive):
    if hashlib.sha256(archive.read_bytes()).hexdigest() != SHA256:
        raise ValueError('tzdata source SHA-256 mismatch')
    names = [line.strip() for line in (ROOT / 'timezones/zones.txt').read_text().splitlines()
             if line.strip() and not line.startswith('#')]
    assert names[:2] == ['GMT', 'UTC'] and len(names) == len(set(names))
    rows = []
    with tempfile.TemporaryDirectory(prefix='apcam-tzdata-') as directory:
        directory = Path(directory)
        with tarfile.open(archive) as source:
            for name in SOURCES:
                (directory / name).write_bytes(source.extractfile(name).read())
            license_text = source.extractfile('LICENSE').read()
        subprocess.run(['zic', '-b', 'fat', '-d', str(directory / 'zones'),
                        *(str(directory / name) for name in SOURCES)], check=True)
        start = int(datetime(2026, 9, 1, tzinfo=timezone.utc).timestamp())
        end = int(datetime(2100, 1, 1, tzinfo=timezone.utc).timestamp())
        samples = {int(datetime(year, month, 15, tzinfo=timezone.utc).timestamp())
                   for year in range(2026, 2100) for month in range(1, 13)}
        for name in names:
            path = directory / 'zones' / name
            data = path.read_bytes()
            rule = data.rsplit(b'\n', 2)[-2].decode('ascii')
            if not rule or '"' in rule or '\\' in rule:
                raise ValueError(f'{name}: unsupported POSIX footer {rule!r}')
            # The ZR10 uClibc parser only accepts nonnegative transition
            # hours up to 24; IANA extensions such as /26 fall back to UTC.
            if any(int(hour) < 0 or int(hour) > 24
                   for hour in re.findall(r"/([+-]?\d+)", rule)):
                raise ValueError(f'{name}: transition hour unsupported by uClibc: {rule}')
            os.environ['TZ'] = rule
            time.tzset()
            with path.open('rb') as stream:
                zone = ZoneInfo.from_file(stream, key=name)
            checks = {t for t in samples if t >= start} | {t + delta for t in transitions(data)
                                if start <= t < end for delta in (-1, 0, 1)}
            for timestamp in checks:
                expected = datetime.fromtimestamp(timestamp, zone)
                actual = time.localtime(timestamp)
                if (actual.tm_gmtoff, actual.tm_zone) != (int(expected.utcoffset().total_seconds()), expected.tzname()):
                    raise ValueError(f'{name}: {rule}: differs at {timestamp}: {actual.tm_gmtoff, actual.tm_zone} != {expected.utcoffset(), expected.tzname()}')
            rows.append(f'    {{"{name}", "{rule}"}},')
    output = ('// Generated by tools/build_timezones.py from IANA tzdata ' + VERSION + '.\n'
              '// Source SHA-256: ' + SHA256 + '\n'
              '// Current/future rules, verified for September 2026 through 2099; not historical tzdata.\n'
              '#pragma once\n\nnamespace APC_Timezone {\n'
              'struct Zone { const char *name; const char *rule; };\n'
              'inline constexpr Zone zones[] = {\n' + '\n'.join(rows) + '\n};\n}\n')
    (ROOT / 'include/apcam/timezones.h').write_text(output)
    (ROOT / 'timezones/LICENSE').write_bytes(license_text)
    print(f'Generated {len(rows)} named timezone rules from IANA {VERSION}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path, help=f'tzdata{VERSION}.tar.gz from data.iana.org')
    generate(parser.parse_args().source)
