#!/usr/bin/env python3
"""ZR10 customer-only SD format, also generating the web validator's header.

U-Boot reads the first 16 KiB as commands and the named partition payload.
Our CRC footer detects corruption; it is not a signature. Preserve the stock
24-byte trailer convention (12345678 followed by the first 16 script bytes).
"""
import argparse
from pathlib import Path
import struct
import zlib

SCRIPT_SIZE = 0x4000
CUSTOMER_SIZE = 0x6B0000
MAGIC = b'ZR10AP01'
TRAILER_SIZE = 36
FIRMWARE_SIZE = SCRIPT_SIZE + CUSTOMER_SIZE + TRAILER_SIZE
SCRIPT_PATH = Path(__file__).resolve().parents[1] / 'packaging/zr10/upgrade_script.txt'


def script_header():
    script = SCRIPT_PATH.read_bytes()
    if len(script) >= SCRIPT_SIZE or not script.endswith(b'% <- this is end of script symbol\n'):
        raise ValueError('Invalid upgrade script')
    return script.ljust(SCRIPT_SIZE, b'\xff')


def pack(customer):
    if len(customer) != CUSTOMER_SIZE or customer[:2] != b'\x85\x19':
        raise ValueError('Expected a padded little-endian JFFS2 customer partition')
    contents = script_header() + customer
    return contents + MAGIC + struct.pack('<I', zlib.crc32(contents)) + b'12345678' + contents[:16]


def validate(contents):
    if len(contents) != FIRMWARE_SIZE or contents[:SCRIPT_SIZE] != script_header():
        raise ValueError('Firmware size or script differs from the customer-only format')
    if contents[SCRIPT_SIZE:SCRIPT_SIZE+2] != b'\x85\x19' or pack(contents[SCRIPT_SIZE:-TRAILER_SIZE]) != contents:
        raise ValueError('Invalid JFFS2 magic, trailer or CRC')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest='command', required=True)
    header = sub.add_parser('header')
    header.add_argument('output', type=Path)
    package = sub.add_parser('pack')
    package.add_argument('customer', type=Path)
    package.add_argument('output', type=Path)
    check = sub.add_parser('check')
    check.add_argument('image', type=Path)
    args = parser.parse_args()
    if args.command == 'header':
        script = SCRIPT_PATH.read_bytes()
        # Adjacent C strings, each escaped independently.
        text = ''.join('    "' + ''.join(f'\\x{b:02x}' for b in line) + '"\n'
                       for line in script.splitlines(keepends=True))
        contents = ('/* Generated by tools/zr10_firmware.py; do not edit. */\n'
                    f'#define ZR10_SCRIPT_SIZE {SCRIPT_SIZE}U\n'
                    f'#define ZR10_CUSTOMER_SIZE {CUSTOMER_SIZE}U\n'
                    f'#define ZR10_FIRMWARE_SIZE {FIRMWARE_SIZE}U\n'
                    'static const unsigned char zr10_upgrade_script[] =\n' + text + ';\n')
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(contents)
    elif args.command == 'pack':
        args.output.write_bytes(pack(args.customer.read_bytes()))
    else:
        validate(args.image.read_bytes())
        print(f'Validated customer-only ZR10 image: {args.image}')


if __name__ == '__main__':
    main()
